theme: jekyll-theme-cayman

title: "Econ Data Science"

plugins:
  - jemoji
  
markdown: kramdown
kramdown:
  parse_block_html: true

# Change Notes:
# changed markdown generator from CommonMarkGhPages to kramdown to render the tables properly. Although CommonMarkGhpages worked nicely with collapsible section. It was ineffective for the tables. 
# source: 
# added "parse_block_html" so that the collapsible sections are rendered properly
  # also removed summary tag from collapsible section as HTML can't read display and summary tags togther. 
  # Sourrce: https://github.com/gettalong/kramdown/issues/155#issuecomment-339714578
